# Generated by Django 3.1.14 on 2022-03-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_auto_20220321_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
