# Generated by Django 3.1.14 on 2022-03-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_bussroute'),
        ('passengers', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leg_buss_route', to='buses.bussroute'),
        ),
    ]
