# Generated by Django 3.1.14 on 2022-03-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_driver'),
        ('buses', '0001_initial'),
        ('routes', '0001_initial'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='destination',
        ),
        migrations.AddField(
            model_name='journey',
            name='buss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buss'),
        ),
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='passengers.driver'),
        ),
        migrations.AddField(
            model_name='journey',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger'),
        ),
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
        migrations.AddField(
            model_name='journey',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
