# Generated by Django 3.1.14 on 2022-03-24 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_driver'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buss',
            name='name',
        ),
        migrations.AddField(
            model_name='buss',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passengers.driver'),
        ),
    ]
