# Generated by Django 3.1.14 on 2022-03-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_driver'),
        ('buses', '0002_auto_20220323_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buss',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_buss', to='passengers.driver'),
        ),
    ]
