# Generated by Django 3.1.14 on 2022-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_auto_20220324_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('A', 'Seat A'), ('B', 'Seat B'), ('C', 'Seat C'), ('D', 'Seat D'), ('E', 'Seat E'), ('F', 'Seat F'), ('G', 'Seat G'), ('H', 'Seat H'), ('I', 'Seat I'), ('J', 'Seat J')], max_length=50, null=True)),
            ],
        ),
    ]
