# Generated by Django 3.1.14 on 2022-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='seats',
            field=models.ManyToManyField(blank=True, to='buses.Seat'),
        ),
    ]
