# Generated by Django 3.1.14 on 2022-03-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('buses', '0005_buss_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(null=True)),
                ('buss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buss_buss_route', to='buses.buss')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_buss_route', to='routes.route')),
            ],
        ),
    ]
